apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: todolist-nginx
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      resolver kube-dns.kube-system.svc.cluster.local valid=10s ipv6=off;

      set $backend_upstream backend.todolist.svc.cluster.local:3001;
      set $frontend_upstream frontend.todolist.svc.cluster.local:3000;

      location /api/ {
        proxy_pass http://$backend_upstream/api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      location / {
        proxy_pass http://$frontend_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
